export const Role = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  CORPORATE_OFFICE: 'CORPORATE_OFFICE',
  SECTOR_HEAD: 'SECTOR_HEAD',
  PROJECT_HEAD: 'PROJECT_HEAD',
} as const;
export type Role = (typeof Role)[keyof typeof Role];

export const ProjectStatus = { PLANNING: 'PLANNING', IN_EXECUTION: 'IN_EXECUTION', COMPLETED: 'COMPLETED', ON_HOLD: 'ON_HOLD' } as const;
export const TaskStatus = { NOT_STARTED: 'NOT_STARTED', IN_PROGRESS: 'IN_PROGRESS', COMPLETED: 'COMPLETED', ON_HOLD: 'ON_HOLD' } as const;
export const QuotationRequestStatus = { DRAFT: 'DRAFT', QUOTES_PENDING: 'QUOTES_PENDING', COMPARISON: 'COMPARISON', WINNER_SELECTED: 'WINNER_SELECTED', PO_CREATED: 'PO_CREATED', CANCELLED: 'CANCELLED' } as const;
export const POStatus = { DRAFT: 'DRAFT', PENDING_APPROVAL: 'PENDING_APPROVAL', APPROVED: 'APPROVED', REJECTED: 'REJECTED', RETURNED: 'RETURNED', SENT_TO_VENDOR: 'SENT_TO_VENDOR' } as const;
export const PaymentRequestStatus = { DRAFT: 'DRAFT', PENDING_APPROVAL: 'PENDING_APPROVAL', APPROVED: 'APPROVED', REJECTED: 'REJECTED', RETURNED: 'RETURNED', PAID: 'PAID' } as const;
export const InvoiceType = { PROFORMA: 'PROFORMA', TAX: 'TAX' } as const;
export const InvoiceStatus = { DRAFT: 'DRAFT', ISSUED: 'ISSUED', CANCELLED: 'CANCELLED' } as const;
